# 正式環境（GCP）：docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d
services:
  nginx:
    ports:
      - "80:80"
      - "443:443"

  mysql:
    ports:
      - "3306:3306"

  redis:
    ports:
      - "6379:6379"
